name: mcquill
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  drift: ^2.34.1
  drift_flutter: ^0.3.1
  flutter:
    sdk: flutter
  go_router: ^17.3.0
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.34.0
  build_runner: ^2.15.1

flutter:
  uses-material-design: true
